### ISSUE TITLE
Ted.com scraping results: Successful: 0 Failed: 0

### ISSUE THREAD

**Issue by gertva** [corralm/TEDscraper#15]
Hi all, I'm not sure what is going on. No matter what language I try to download I get this:
![image](https://user-images.githubusercontent.com/8968570/95958954-26496600-0e02-11eb-890f-d378b39633b7.png)
ted_talks.csv contains a header and one record. 
Thanks for letting me know how I can fix this.

**Comment by corralm** [comment]
Hi there – I'm getting the same results. I'll look into this issue.

Thanks,
Miguel

**Comment by corralm** [comment]
Unfortunately, it looks like TED made some changes to its website code. 
I don't have the bandwidth to make the appropriate changes at this time – sorry :flushed: 

I'll update the README to let others know. Thanks
